//Import Task Model
const task = require("../models/task_models");

//create the task controller object and functions
const taskController = {


    createTask: (req, res) => {

        //grabbing title and is_completed from the body
        const newTitle = req.body.title;
        const new_is_completed = req.body.is_completed;

        //checking if empty
        if (!newTitle || new_is_completed == null) {
            //Return error message if empty
            return res.status(400).json({message: "Title and completion state are required"});
        };


        //creating task object
        const newTask = {
            title: newTitle,
            is_completed: new_is_completed
        };

        //saving the object in database
        task.createTask(newTask, (error, results) => {

            //error checking
            if(error) {
                return res.status(500).json({
                    message: "Database error"
                });
            }

            //if no error, will not return so success code will run
            res.status(200).json({
                message: "Task created successfully",

                //sends id generated by mysql
                id: results.insertId
            });
        })

    },

    //controller to get all task
    getAllTasks: (req, res) => {

        task.getAllTasks((error, results) => {

            //error handling
            if (error) {
                return res.status(500).json({message: "Database error"})
            }

            //sending all data as json
            return res.status(200).json(results);

        });
    },

    getTaskById: (req, res) => {

        const taskId = req.params.id;

        task.getTaskById(taskId, (error, results) => {
             //if there is no error 
            if (!error) {

                //if no results found, no result sent
                if (results.length === 0) {
                    return res.status(404).json({
                        message: "Task not found"
                    });
                } else {
                    //return first task found 
                    return res.status(200).json(results[0]);
                }

            } else {
                return res.status(500).json({
                    message: "Database error"
                });
            };


        })

       
    },

    updateTask: (req, res) => {

        //grabbing title and is_completed from the body
        const id = req.params.id;
        const title = req.body.title;
        const is_completed = req.body.is_completed;

        //checking if empty
        if (!title || is_completed == null) {
            //Return error message if empty
            return res.status(400).json({message: "ID,  Title and completion state are required"});
        };


        //creating task object
        const task = {
            title: title,
            is_completed: is_completed
        };

        task.updateTask(id, task, (error, results) => {

            //Error handling
            if (!error) {
                //no errors but no rows affected
                if (results.affectedRows === 0) {
                    return res.status(404).json({
                        message: "Task not found"
                    })
                } else {
                    // no erros and 1 row changed, success
                    return res.status(200).json({
                        message: "Task updated successfully"
                    })
                };

            } else {
                //error present
                return res.status(500).json({
                    message: "Database error"
                })
            };
        });

    },

    deleteTask: (req, res) => {


        const taskId = req.params.id;

        task.deleteTask(taskId, (error, results) => {

            if (!error) {
                //if no error, check if row deleted
                if (results.affectedRows === 0) {
                    //if no rows were affected, no task was deleted
                    return res.status(404).json({
                        message: "Task not found"
                    });
                } else {
                    //then operatio was a success
                    return res.status(200).json({
                        message: "Task deleted successfully"
                    });
                };             

            } else {
                return res.status(500).json({
                    message: "Database error"
                });
            };

        });

    }


};

//exports controller, will be used by routes
module.exports = taskController;