//Import Task Model
const task = require("../models/task_models");

//create the task controller object and functions
const taskController = {


    createTask: (res,req) => {

        //grabbing title and is_completed from the body
        const title = req.body.title;
        const is_completed = req.body.is_completed;

        //checking if empty
        if (!title || is_completed == null) {
            //Return error message if empty
            return res.status(400).json({message: "Title and completion state are required"});
        };


        //creating task object
        const task = {
            title: title,
            is_completed: is_completed
        };

        //saving the object in database
        task.createTask(task, (error,results) => {

            //error checking
            if(error) {
                return res.status(500).json({
                    message: "Databse error"
                });
            }

            //if no error, will not return so success code will run
            res.status(200).json({
                message: "Task created successfully",

                //sends id generated by mysql
                id: results.insertId
            });
        })

    },

    //controller to get all task
    getAllTasks: (res, req) => {

        task.getAllTasks((error, results) => {

            //error handling
            if (error) {
                return res.status(500).json({message: "Database error"})
            }

            //sending all data as json
            res.status(200).json(results);

        });
    },

    getTaskById: (res,req) => {

        const taskId = req.params.id;

        task.getTaskById(taskId, (error, results) => {
             //if there is no error 
            if (!error) {

                //if no results found, no result sent
                if (results.length === 0) {
                    return res.status(404).json({
                        message: "Task not found"
                    });
                } else {
                    //return first task found 
                    return res.status(200).json(results[0]);
                }

            } else {
                return res.status(500).json({
                    message: "Database error"
                });
            };


        })

       
    },

    updateTask: (res, req) => {

        

    }




};

//exports controller, will be used by routes
model.exports = taskController;